extract_to: .

Video_html_Code_Snippet: |
    <br>
    <div style="position: relative; display: flex; justify-content: center; align-items: center;">
        <video playsinline=""
            controls="" preload="metadata" src="{new_link}"
            style="display: block; width: 80%; background-color: rgba(255, 255, 255, 0.03);">
        </video>
    </div>
    <br>



html_Head_Code_Snippet: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0">


